//Английские названия жанров (см. server/core/genres/genresText.js).
//sections - по русскому названию раздела, genres - по коду жанра.
//Используется веб-интерфейсом (client/share/i18n.js) и OPDS (server/core/opds/i18n.js).

const sections = {
    'Фантастика': 'Science Fiction & Fantasy',
    'Детективы и Триллеры': 'Detectives & Thrillers',
    'Проза': 'Prose',
    'Любовные романы': 'Romance',
    'Приключения': 'Adventure',
    'Литература для детей': 'Children\'s Literature',
    'Религия, духовность, эзотерика': 'Religion, Spirituality, Esoterics',
    'Поэзия': 'Poetry',
    'Драматургия': 'Drama',
    'Старинное': 'Antique Literature',
    'Фольклор': 'Folklore',
    'Наука, Образование': 'Science & Education',
    'Искусство, Искусствоведение, Дизайн': 'Art, Art History & Design',
    'Техника': 'Technology',
    'Компьютеры и Интернет': 'Computers & Internet',
    'Справочная литература': 'Reference',
    'Документальная литература': 'Nonfiction',
    'Юмор': 'Humor',
    'Дом и семья': 'Home & Family',
    'Прочее': 'Other',
    'Деловая литература': 'Business',
    'Учебники и пособия': 'Textbooks & Study Guides',
    'Неотсортированное': 'Unsorted',
};

const genres = {
    //Фантастика
    sf_history: 'Alternative History',
    sf_action: 'Military SF',
    sf_epic: 'Epic SF',
    sf_heroic: 'Heroic SF',
    sf_detective: 'Detective SF',
    sf_cyberpunk: 'Cyberpunk',
    sf_space: 'Space SF',
    sf_social: 'Social & Psychological SF',
    sf_horror: 'Horror',
    sf_humor: 'Humorous SF',
    sf_fantasy: 'Fantasy',
    sf: 'Science Fiction',
    sf_fantasy_city: 'Urban Fantasy',
    sf_postapocalyptic: 'Post-Apocalyptic',
    sf_litrpg: 'LitRPG',
    sf_etc: 'Speculative Fiction',
    russian_fantasy: 'Slavic Fantasy',
    sf_technofantasy: 'Technofantasy',
    fairy_fantasy: 'Mythological Fantasy',
    hronoopera: 'Chrono-opera',
    sf_mystic: 'Mysticism',
    sf_stimpank: 'Steampunk',
    modern_tale: 'Modern Fairy Tale',
    popadancy: 'Isekai / Accidental Travelers',
    //Детективы и Триллеры
    det_classic: 'Classic Detective',
    det_police: 'Police Procedural',
    det_action: 'Action',
    det_irony: 'Cozy & Ironic Detective',
    det_history: 'Historical Detective',
    det_espionage: 'Spy Detective',
    det_crime: 'Crime',
    det_political: 'Political Detective',
    det_maniac: 'Serial Killers',
    det_hard: 'Hardboiled',
    thriller: 'Thriller',
    detective: 'Detectives',
    det_su: 'Soviet Detective',
    //Проза
    prose: 'Prose',
    prose_classic: 'Classic Prose',
    prose_history: 'Historical Prose',
    prose_contemporary: 'Contemporary Prose',
    prose_counter: 'Counterculture',
    prose_rus_classic: 'Russian Classic Prose',
    prose_su_classics: 'Soviet Classic Prose',
    prose_military: 'War Prose',
    foreign_prose: 'Foreign Classic Prose',
    foreign_antique: 'Medieval Classic Prose',
    literature_18: '17th-18th Century Classic Prose',
    literature_19: '19th Century Classic Prose',
    literature_20: '20th Century Classic Prose',
    gothic_novel: 'Gothic Novel',
    prose_magic: 'Magical Realism',
    epistolary_fiction: 'Epistolary Fiction',
    prose_neformatny: 'Experimental Prose',
    aphorisms: 'Aphorisms & Quotes',
    great_story: 'Novels & Novellas',
    story: 'Short Stories, Essays, Novellas',
    prose_abs: 'Phantasmagoria & Absurdist Prose',
    //Любовные романы
    love_contemporary: 'Contemporary Romance',
    love_history: 'Historical Romance',
    love_detective: 'Romantic Suspense',
    love_short: 'Short Romance',
    love_erotica: 'Erotica',
    love: 'Romance',
    love_sf: 'Romantic Fantasy',
    love_hard: 'Pornography',
    //Приключения
    adv_history: 'Historical Adventure',
    adv_indian: 'Western',
    adv_maritime: 'Sea Adventure',
    adv_geo: 'Travel & Geography',
    adv_animal: 'Nature & Animals',
    adventure: 'Adventure',
    child_adv: 'Adventure for Children & Teens',
    adv_modern: 'Modern Adventure',
    tale_chivalry: 'Chivalric Romance',
    adv_story: 'Picaresque Novel',
    //Литература для детей
    child_tale: 'Fairy Tales of the World',
    child_verse: 'Poems for Children',
    child_prose: 'Prose for Children',
    child_sf: 'SF for Children',
    child_det: 'Children\'s Mystery & Action',
    child_education: 'Children\'s Educational Literature',
    children: 'Children\'s Literature',
    child_classical: 'Classic Children\'s Literature',
    child_tale_rus: 'Russian Fairy Tales',
    foreign_children: 'Foreign Children\'s Literature',
    prose_game: 'Games & Exercises for Children',
    //Религия, духовность, эзотерика
    religion_budda: 'Buddhism',
    sci_religion: 'Religious Studies',
    religion_esoterics: 'Esoterics',
    religion_self: 'Self-Improvement',
    religion: 'Religion',
    religion_christianity: 'Christianity',
    religion_orthodoxy: 'Orthodoxy',
    religion_protestantism: 'Protestantism',
    religion_catholicism: 'Catholicism',
    religion_judaism: 'Judaism',
    religion_hinduism: 'Hinduism',
    religion_islam: 'Islam',
    religion_paganism: 'Paganism',
    astrology: 'Astrology & Palmistry',
    //Поэзия
    poetry: 'Poetry',
    humor_verse: 'Humorous Verse & Fables',
    poetry_classical: 'Classic Poetry',
    poetry_modern: 'Modern Poetry',
    poetry_rus_classical: 'Russian Classic Poetry',
    poetry_rus_modern: 'Modern Russian Poetry',
    poetry_for_classical: 'Foreign Classic Poetry',
    poetry_for_modern: 'Modern Foreign Poetry',
    poetry_east: 'Eastern Poetry',
    lyrics: 'Lyric Poetry',
    song_poetry: 'Song Lyrics',
    poem: 'Epic Poetry',
    palindromes: 'Visual & Experimental Poetry',
    //Драматургия
    dramaturgy: 'Drama',
    comedy: 'Comedy',
    tragedy: 'Tragedy',
    drama: 'Drama',
    drama_antique: 'Ancient Drama',
    screenplays: 'Screenplays',
    vaudeville: 'Mystery Plays, Buffoonery, Vaudeville',
    //Старинное
    antique_ant: 'Ancient Literature',
    antique_european: 'Old European Literature',
    antique_russian: 'Old Russian Literature',
    antique_east: 'Ancient Eastern Literature',
    antique: 'Antique',
    //Фольклор
    antique_myths: 'Myths, Legends, Epics',
    folklore: 'Folklore & Riddles',
    folk_tale: 'Folk Tales',
    epic: 'Bylinas & Epics',
    proverbs: 'Proverbs & Sayings',
    folk_songs: 'Folk Songs',
    child_folklore: 'Children\'s Folklore',
    limerick: 'Chastushkas & Nursery Rhymes',
    //Наука, Образование
    sci_history: 'History',
    sci_psychology: 'Psychology & Psychotherapy',
    sci_philosophy: 'Philosophy',
    sci_politics: 'Politics',
    sci_juris: 'Law',
    sci_linguistic: 'Linguistics & Foreign Languages',
    sci_medicine: 'Medicine',
    sci_phys: 'Physics',
    sci_math: 'Mathematics',
    sci_chem: 'Chemistry',
    sci_biology: 'Biology',
    science: 'Science',
    sci_cosmos: 'Astronomy & Space',
    sci_geo: 'Geology & Geography',
    sci_state: 'State & Law',
    sci_economy: 'Economics',
    sci_medicine_alternative: 'Alternative Medicine',
    sci_philology: 'Literary Studies',
    sci_popular: 'Popular Science',
    military_history: 'Military History',
    sci_social_studies: 'Social Studies & Sociology',
    sci_zoo: 'Zoology',
    sci_botany: 'Botany',
    sci_ecology: 'Ecology',
    sci_oriental: 'Oriental Studies',
    sci_theories: 'Alternative Sciences & Theories',
    sci_veterinary: 'Veterinary Medicine',
    //Искусство, Искусствоведение, Дизайн
    sci_culture: 'Cultural Studies',
    notes: 'Sheet Music',
    nonf_criticism: 'Criticism',
    design: 'Art & Design',
    music: 'Music',
    painting: 'Painting & Art Albums',
    architecture_book: 'Sculpture & Architecture',
    art_world_culture: 'World Art & Culture',
    cine: 'Cinema',
    theatre: 'Theatre',
    art_criticism: 'Art History',
    //Техника
    sci_tech: 'Engineering',
    sci_build: 'Construction & Strength of Materials',
    sci_radio: 'Radio Electronics',
    sci_metal: 'Metallurgy',
    sci_transport: 'Transport & Aviation',
    military_weapon: 'Military Science & Weapons',
    auto_business: 'Automotive',
    equ_history: 'History of Technology',
    //Компьютеры и Интернет
    comp_www: 'OS, Networks & Internet',
    comp_hard: 'Computer Hardware & Signal Processing',
    comp_db: 'Programming & Databases',
    computers: 'Computers',
    tbg_computers: 'Tutorials & Self-Study Guides',
    //Справочная литература
    ref_encyc: 'Encyclopedias',
    ref_dict: 'Dictionaries',
    ref_ref: 'Reference Books',
    ref_guide: 'Guides',
    reference: 'Reference',
    geo_guides: 'Travel Guides, Maps & Atlases',
    //Документальная литература
    nonf_biography: 'Biographies & Memoirs',
    nonf_publicism: 'Journalism & Essays',
    nonfiction: 'Nonfiction',
    nonf_military: 'Military Nonfiction',
    military_special: 'Military Affairs',
    travel_notes: 'Geography & Travel Notes',
    //Юмор
    humor_anecdote: 'Jokes',
    humor_prose: 'Humorous Prose',
    humor: 'Humor',
    humor_satire: 'Satire',
    //Дом и семья
    home_cooking: 'Cooking',
    home_pets: 'Pets',
    home_crafts: 'Hobbies & Crafts',
    home_entertain: 'Entertainment',
    home_health: 'Health',
    home_garden: 'Gardening',
    home_diy: 'Do It Yourself',
    home_sport: 'Martial Arts & Sports',
    home_sex: 'Relationships & Sex',
    home: 'Housekeeping',
    sci_pedagogy: 'Pedagogy & Parenting',
    auto_regulations: 'Cars & Traffic Rules',
    home_collecting: 'Collecting',
    family: 'Family Relationships',
    //Прочее
    other: 'Unsorted',
    periodic: 'Magazines & Newspapers',
    comics: 'Comics',
    unfinished: 'Unfinished',
    fanfiction: 'Fan Fiction',
    network_literature: 'Self-Published & Web Literature',
    //Деловая литература
    banking: 'Finance',
    org_behavior: 'Marketing & PR',
    popular_business: 'Career & HR',
    economics_ref: 'Business Literature',
    economics: 'Economics',
    //Учебники и пособия
    sci_textbook: 'Textbooks & Study Guides',
    tbg_school: 'School Textbooks',
    tbg_secondary: 'Secondary & Vocational Textbooks',
    tbg_higher: 'University Textbooks',

    //не-fb2 жанры
    study: 'Educational Literature',
    study_preschool: 'For Preschoolers',
    study_scool: 'For Schoolchildren',
    study_students: 'For Students',
    study_graduate: 'For Graduate Students',
    home_child: 'Children & Parenting',
    home_handiwork: 'Needlework & Housekeeping',
    arts: 'Art',
    arts_albums: 'Art & Photo Albums',
    art_visual: 'Visual Arts & Architecture',
    art_sci: 'Art History',
    art_film: 'Film Studies',
    art_dance: 'Dance & Choreography',
    art_theater: 'Theatre & Stage Arts',
    languages: 'Foreign Languages',
    lang_rus: 'Russian Language',
    lag_eng: 'English Language',
    lang_eng_textbook: 'English: Textbooks',
    lang_eng_dict: 'English: Dictionaries',
    lang_eng_read: 'English: Home Reading',
    lang_eng_theor: 'English: Theory & History',
    lang_eng_phrase: 'English: Phrasebooks',
    lang_arab: 'Arabic Language',
    lang_east: 'Eastern Languages',
    lang_euro: 'European Languages',
    lang_spanish: 'Spanish Language',
    lang_it: 'Italian Language',
    lang_chi: 'Chinese Language',
    lang_korean: 'Korean Language',
    lang_lat: 'Latin Language',
    lang_de: 'German Language',
    lang_pl: 'Polish Language',
    lang_tu: 'Turkish Language',
    lang_fr: 'French Language',
    lang_jap: 'Japanese Language',
    lang_greek: 'Ancient Greek & Other Ancient Languages',
    comp_soft_office: 'Office Software',
    comp_db_db2: 'DB2',
    comp_db_mysql: 'MySQL',
    comp_db_mssqlserver: 'MS SQL Server',
    comp_db_oracle: 'Oracle',
    comp_db_postgresql: 'PostgreSQL',
    comp_db_sqlite: 'SQLite',
    comp_db_sybase: 'Sybase SQL',
    comp_dv_ai: 'Artificial Intelligence',
    comp_db_exp: 'Expert Systems',
    comp_design: 'Graphics, Design & Multimedia',
    comp_www_html: 'HTML',
    comp_www_css: 'CSS',
    comp_www_cms: 'CMS',
    comp_security: 'Computer Security',
    comp_osnet: 'Networks',
    comp_soft: 'Computers & Software',
    comp_os: 'Operating Systems',
    comp_os_windows: 'Windows',
    comp_os_linux: 'Linux',
    comp_os_unix: 'UNIX',
    comp_soft_dev: 'Software Development',
    comp_soft_dev_alg: 'Algorithms',
    comp_soft_dev_man: 'Management',
    comp_soft_dev_debug: 'Debugging',
    comp_soft_cad: 'CAD Systems',
    comp_programming: 'Programming Languages & Systems',
    comp_prog_delphi: 'Delphi',
    comp_prog_pascal: 'Pascal',
    comp_prog_c: 'C',
    comp_prog_cpp: 'C++',
    comp_prog_gnuc: 'GNU C++',
    comp_prog_msvc: 'MS Visual Studio',
    comp_prog_qt: 'Qt',
    comp_prog_csharp: 'C#',
    comp_prog_java: 'Java',
    comp_prog_js: 'JavaScript',
    comp_prog_php: 'PHP',
    comp_prog_pyton: 'Python',
    comp_prog_ror: 'Ruby',
    comp_dig_photo: 'Digital Photography',
    comp_exam: 'Certification Exams',
    turism: 'Travel & Tourism',
    auto: 'Cars',
    fish: 'Fishing',
    hunt: 'Hunting',
    sport: 'Sports',
    sci_tech_industry: 'Industry',
    sci_tech_oil: 'Oil & Gas',
    sci_tech_machinery: 'Mechanical Engineering',
    sci_tech_print: 'Printing',
    sci_tech_chem: 'Chemical Industry',
    sci_tech_sopromat: 'Strength of Materials',
    sci_tech_theormech: 'Theory of Machines',
    sci_tech_ref: 'Technical Reference',
    sci_energy: 'Power & Electrical Engineering',
    sci_phys_acustics: 'Acoustics',
    sci_phys_quant: 'Quantum Mechanics & Field Theory',
    sci_phys_math: 'Mathematical Physics',
    sci_phys_molecular: 'Molecular Physics',
    sci_phys_gen: 'General Physics',
    sci_phys_optics: 'Optics',
    sci_phys_theor: 'Theoretical Physics',
    sci_phys_thermo: 'Thermodynamics & Statistical Physics',
    sci_phys_plasma: 'Plasma Physics',
    sci_phys_nuclear: 'Nuclear & Particle Physics',
    sci_phys_solidstate: 'Solid-State Physics & Crystallography',
    sci_phys_em: 'Electricity & Magnetism',
    sci_phys_ref: 'Physics Reference',
    sci_hem_general: 'General Chemistry',
    sci_orgchem: 'Organic Chemistry',
    sci_anachem: 'Analytical Chemistry',
    sci_physchem: 'Physical Chemistry',
    sci_biophys: 'Biophysics',
    sicial: 'Social Sciences & Humanities',
    sicial_var: 'Military, Weapons & Intelligence',
    sicial_hist: 'History, Archaeology & Ethnography',
    sicial_lit: 'Literary Studies & Folklore',
    sicial_ped: 'Pedagogy',
    sicial_pol: 'Politics',
    sicial_law: 'Law',
    sicial_psi: 'Psychology',
    sicial_sicial: 'Sociology',
    sicial_smi: 'Mass Media & Publishing',
    sicial_stat: 'Statistics & Demography',
    sicial_phy: 'Philosophy',
    sicial_lang: 'Linguistics & Philology',
    periodic_newspaper: 'Newspapers',
    periodic_mag: 'Magazines',
};

module.exports = {sections, genres};
